version: '3.8'

services:
  php-apache-environment:
    build:
      context: .
      dockerfile: PhpDockerfile
    image: eclipx-php-test
    ports:
      - 8000:80
    depends_on:
      - db-eclipx
    volumes:
      - ./src:/srv/app
    environment: 
      - DOCUMENT_ROOT_CONTEXT=public
      - ALLOW_OVERRIDE_OPTION=All
      - APPLICATION_ENV_OPTION=development
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db-eclipx:
    container_name: db-eclipx
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: mysqltest
        MYSQL_DATABASE: accounts
        MYSQL_USER: accounts_adm
        MYSQL_PASSWORD: accounts_test
    volumes:
      - ./dbs:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d/:ro
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8008:80'
    restart: always
    environment:
      PMA_HOST: db-eclipx
    depends_on:
      - db-eclipx
volumes: 
  db-eclipx:
